circuit_knitting_toolbox/circuit_cutting/__init__.py, circuit_knitting_toolbox/circuit_cutting/wire_cutting/wire_cutting.py, circuit_knitting_toolbox/circuit_cutting/wire_cutting/wire_cutting_post_processing.py, circuit_knitting_toolbox/circuit_cutting/wire_cutting/wire_cutting_verification.py
The most important change is in `__init__.py`.  The others changes are to fix formatting issues and a few Sphinx warnings (which would otherwise be treated as errors, since we are passing the `-W` flag to Sphinx).
=> Add circuit cutting API references to Sphinx build

.github/workflows/coverage.yml
coverage 7.0.0 removed `FnmatchMatcher`, which coverage-lcov currently depends on.
https://github.com/chaychoong/coveragepy-lcov/issues/5
We can unpin this once coverage-lcov has been fixed.
=> Pin coverage to < 7 when running coveragepy-lcov

README.md
I've also fixed the link for the "stability" badge
Preview at https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/add-badges/README.md
=> Add Black and Coveralls badges to README

circuit_knitting_toolbox/circuit_cutting/wire_cutting/wire_cutting_evaluation.py
This allows someone to run the subcircuits using the `Sampler` of their choice, i.e., not limited to choosing between `qiskit.primitives` and `qiskit_ibm_runtime`.
=> Add `run_subcircuits_using_sampler` function

.github/dependabot.yml
This will allow dependabot to automatically open PRs to update the versions of the GitHub Actions that we use.  This PR was made by following instructions at https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> Configure dependabot to keep GitHub Actions versions up to date

pyproject.toml
`qiskit-ibmq-provider` has been deprecated as of Qiskit 0.40.  We actually don't seem to be using it at all in ckt anymore, so we can safely remove it from the dependencies.
=> Remove dependency on `qiskit-ibmq-provider`

circuit_knitting_toolbox/circuit_cutting/wire_cutting/wire_cutting.py
Wire cutting has several deprecated usages of `Bit`, which should be updated.
=> Fix deprecated usages of Bit

circuit_knitting_toolbox/entanglement_forging/entanglement_forging_ground_state_solver.py, docs/conf.py
I've had this branch sitting locally for a while; I think it's time to contribute it.
- Use appropriate exceptions instead of `AttributeError`
- Use tuple unpacking rather than indexing (will catch errors better)
- raise `NotImplementedError` for methods not implemented
- Remove double variable assignment in `docs/conf.py`
=> A few small improvements

.github/workflows/docs.yml, .github/workflows/lint.yml, docs/conf.py, docs/index.rst, docs/release-notes.rst, pyproject.toml, releasenotes/config.yaml, tox.ini
This adds support for reno, so that we can have an explicit "release notes" section in our docs.  This also puts us in line with the practices of Qiskit and the Qiskit application modules.
This will be distinct from the PR summary that gets added to the [release page](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/releases) for each release.  It will allow us to more thoroughly document new features, deprecations, and other changes in the toolbox.
=> Add support for reno release notes

pyproject.toml
Upon the next release, this will enable urls for the repo and docs to be shown on pypi.
=> Add `project.urls` to `pyproject.toml`

circuit_knitting_toolbox/__init__.py
In order to give users following the `main` branch even more of a "heads up" about the pending removal of Python 3.7 support, we can merge this PR immediately, which will warn them if they are using Python 3.7.  Then, we can wait and merge #80 later (in a few weeks, most likely), just before we want to add code that supports only Python 3.8 and higher.
I did not add a release note here, because we have no plans to make another release before dropping Python 3.7 support.
=> Deprecate support for Python 3.7

circuit_knitting_toolbox/entanglement_forging/entanglement_forging_knitter.py
The Estimator no longer needs all circuits up front. Instead, the preferable usage is to just pass in the circuits you want to evaluate when `run` is called.
This PR cleans up some deprecation warnings being thrown during testing
=> Update usage of Qiskit Estimator

tools/extremal_dependency_versions.py
Now that https://github.com/Qiskit/qiskit-nature/pull/1142 has been merged, our "development version tests" are going to [fail](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/actions/runs/4826062552) on `main` until #83 is merged.  This change fixes CI immediately by excluding the development version of qiskit-nature from these tests.  This change should be reverted as part of #83 before it is merged.
=> Temporarily disable qiskit-nature development version test

.github/workflows/coverage.yml
I noticed when tracking down a [coveralls failure](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/pull/120#issuecomment-1527727777) that we are using the `master` version of the workflow, even though the [README](https://github.com/marketplace/actions/coveralls-github-action) now suggests to use `v2`.  Here, I've updated this.  There's no good reason at this point to rely explicitly on their development version.
=> Use a released version of the coveralls workflow

docs/tutorials/circuit_cutting/tutorial_3_cutting_with_quantum_serverless.ipynb, pyproject.toml
Updates `tutorial_3_cutting_with_quantum_serverless` to incorporate some of the more recent changes made to quantum-serverless:
* use `@distribute_task()` decorator instead of `@run_qiskit_remote()`
* use `with serverless.context():` instead of `with serverless:`
As a result, users will no longer get deprecation warnings  when running the notebook
=> Remove severless deprecations in cutting tutorial

docs/tutorials/entanglement_forging/tutorial_2_forging_with_quantum_serverless.ipynb
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
Updates tutorial_2_forging_with_quantum_serverless to incorporate some of the more recent changes made to quantum-serverless:
* use @distribute_task() decorator instead of @run_qiskit_remote()
* use with serverless.context(): instead of with serverless:
As a result, users will no longer get deprecation warnings when running the notebook
=> Remove serverless deprecations in forging tutorial

README.md
#122 updates the dependency versions but not the badges.  This fixes that.  (Sorry, I meant to suggest this before merging #122, but I forgot to.)
=> Update Qiskit badges following #122

releasenotes/notes/deprecate-py37-5ef642682641aeb8.yaml
Python 3.7 was deprecated in #87, but we did not add a release note then because we did not expect to make a release before removing Python 3.7 support.  Now, plans have changed, so we should add the note.
=> Add release note following Python 3.7 deprecation

circuit_knitting_toolbox/circuit_cutting/wire_cutting/mip_model.py
This improves the error messages when cplex is not installed.  Closes #119.
Formerly:
> RuntimeError: dictionary changed size during iteration
With this change:
> DOcplexException: Cannot solve model: no CPLEX runtime found.
Also, I removed an unnecessary line and fixed a deprecation notice which said:
> DeprecationWarning: Model.get_solve_status() is deprecated with cloud solve, use Model.solve_details instead
Initially, I was going to add this change to #109, but then I decided that it is so basic that it should really go in first.
=> Improve errors when cplex is not installed

pyproject.toml
This will allow users to `pip install circuit-knitting-toolbox[pyscf]` or `pip install circuit-knitting-toolbox[pyscf,cplex]` if they want everything.  (`pip install circuit-knitting-toolbox[notebook-dependencies]` already installs both, and a few other things.)  This also removes duplication of the desired `pyscf` version.
=> List `pyscf` explicitly as an optional dependency

circuit_knitting_toolbox/entanglement_forging/entanglement_forging_ground_state_solver.py, circuit_knitting_toolbox/entanglement_forging/entanglement_forging_knitter.py
This PR is meant to just clean up a few remaining confusing/incorrect/messy things in the entanglement forging docstrings
=> General cleanup ef

releasenotes/config.yaml
This replaces the header "0.1.0-1" (or similar) at https://qiskit-extensions.github.io/circuit-knitting-toolbox/release-notes.html with "Upcoming release (`main` branch)".
=> Set unreleased version title in reno config

.github/workflows/test_development_versions.yml, .github/workflows/test_latest_versions.yml, .github/workflows/test_minimum_versions.yml, test/conftest.py, test/entanglement_forging/test_entanglement_forging_ground_state_solver.py, test/entanglement_forging/test_entanglement_forging_knitter.py, tox.ini
This marks a number of the entanglement forging tests as being "slow."  These slow tests are run by default (and in CI), but they can be excluded by passing the option `--skip-slow` to pytest.  For instance, the command `tox -epy3 -- --skip-slow` runs very quickly.
I am hoping that this helps us iterate more quickly, as the code we are soon to migrate over has a very nice test suite with 100% coverage that executes in only a few seconds.
=> Skip slow tests by default (but not in CI)

circuit_knitting_toolbox/utils/simulation.py, test/utils/test_simulation.py
This adds support for reset operations to the simulator.  In doing so, it also removes the restriction that classical bits can only be written once.
This change is necessary to support the tests for wire cutting.
=> Add `Reset` support to the simulator

circuit_knitting_toolbox/circuit_cutting/cutting_decomposition.py, circuit_knitting_toolbox/circuit_cutting/qpd/qpd.py
Currently, there are a few loops that use the variable `gate` for a `CircuitInstruction`.  This changes those to use the variable name `instruction` instead.  This removes the nonsensical `gate.operation` phrasing.  (`.operation` _might_ be a gate, but it is not in general.)
=> Change `gate.operation` -> `instruction.operation`

circuit_knitting_toolbox/circuit_cutting/qpd/qpd_basis.py, test/circuit_cutting/qpd/test_qpd_basis.py
`QPDBasis` has a property called `kappa`, but that is hardly a standard name.  It's defined in https://arxiv.org/abs/2205.00016, but the first author of that paper instead uses the term "C-factor" is his [master thesis](https://www.research-collection.ethz.ch/handle/20.500.11850/504508).  Another paper, https://arxiv.org/abs/2006.11174, uses the symbol `W(U)` for the same quantity.  `gamma` is perhaps more well established, but it refers specifically to the _optimal_ value of kappa, and we may do decompositions that are less than optimal.
Thus, this introduces a property called `overhead`, which _is_ a standard term to represent kappa^2.  This is typically the quantity we are interested in, so we can show query it in the tutorials instead of computing kappa^2.
=> Add `overhead` property to `QPDBasis`

.github/dependabot.yml
This enables monthly dependabot updates for all packages whose versions are precisely pinned in `pyproject.toml`, which for us is various linters.  This way, we will have a sense of (i) which linters have updates available; (ii) which linters can be updated immediately without causing any errors; and (iii) when a linter can't be immediately updated, an automated CI log of what first needs to be fixed.  I believe monthly is the appropriate cadence for these checks; I really don't want to be bothered more often than that with linter updates, but I don't want them to get _way_ out of date either without us noticing.
One thing that _might_ become annoying is various black updates, but if that occurs we can later tell dependabot to ignore them.
I first experimented with this on a personal fork …
=> Enable monthly dependabot updates for the linters

circuit_knitting_toolbox/utils/simulation.py, test/utils/test_simulation.py
Closes #158
This works around
- https://github.com/Qiskit/qiskit-terra/issues/9657
- https://github.com/Qiskit/qiskit-aer/issues/1810
- https://github.com/Qiskit/qiskit-aer/issues/1811
=> Implement exact sampler

circuit_knitting_toolbox/circuit_cutting/qpd/qpd.py, test/circuit_cutting/qpd/test_qpd.py
This changes `generate_qpd_samples` to use exact weights when it's possible for _all_ of them, i.e., it's either all or nothing, for now at least.  I am working on a subsequent PR that will allow a mixture: the weights above the `1 / num_samples` threshold will be evaluated exactly, while everything else will be sampled.   However, that's a bit more complex, and this will suffice for some of the basic use cases (e.g., cutting CNOTs only).
=> Use exact weights in `generate_qpd_samples` when it's possible for _all_ of them

tox.ini
Even though the coverage workflow passes CI, it's been failing for Caleb and me locally.  Specifically, it's erroneously showing that the following `continue` statement is not covered:
https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/b919f99d2ab6b54e63397769697ba19b2363ab62/circuit_knitting_toolbox/circuit_cutting/cutting_decomposition.py#L65-L70
After discovering the comment at https://github.com/nedbat/coveragepy/issues/1530#issuecomment-1520879380, I decided to try setting the Python version to 3.10, as that's what CI uses.  With this change, the coverage workflow now passes for me locally.
I am not sure if this has the same root problem at https://github.com/nedbat/coveragepy/issues/1530, but I suspect that it may.
=> Update `tox.ini` to use Python 3.10 in coverage workflow

circuit_knitting_toolbox/circuit_cutting/qpd/qpd.py, test/circuit_cutting/qpd/test_qpd.py
This change allows `num_samples` to be a float.  This really only has one immediate impact: one can pass `math.inf` as `num_samples` and get exact weights (no sampled ones) no matter what.  While ordinarily the weights will all add up to `num_samples,` this is not possible when `num_samples == math.inf`, so the weights instead add up to 1 in this special case.
Otherwise, this is the first step in preparation for my PR that will allow both sampled and exact values to be returned together -- so it's not all or nothing (#190).
Why does a float as `num_samples` make sense in general?  There is this special threshold given by `1 / num_samples`, and this change allows tweaking this threshold arbitrarily.
=> Allow `num_samples` to be a float

circuit_knitting_toolbox/entanglement_forging/entanglement_forging_knitter.py
This branch is from November 4, 2022.  Looks like I forgot to open the corresponding PR.
It's a protected function, so not a big deal, but we might as well merge it.
=> Update a docstring

circuit_knitting_toolbox/utils/__init__.py, circuit_knitting_toolbox/utils/bitwise.py, circuit_knitting_toolbox/utils/conversion.py, circuit_knitting_toolbox/utils/iteration.py, circuit_knitting_toolbox/utils/metrics.py, circuit_knitting_toolbox/utils/observable_grouping.py, circuit_knitting_toolbox/utils/orbital_reduction.py, circuit_knitting_toolbox/utils/simulation.py, circuit_knitting_toolbox/utils/transforms.py, tox.ini
This improves the API docs within the utils, by showing each utility module separately on the utils page.  I've also enabled Sphinx parallel build to save time (45 seconds, down from 75 seconds before).
=> Improve the API reference docs within the utils directory

circuit_knitting_toolbox/utils/simulation.py, test/utils/test_simulation.py
Partially addresses #180
This also adds a test to make sure the simulator rejects a circuit with classical control flow, for now.
=> Fix the exact simulator to error on classical conditions

pyproject.toml, tox.ini
I noticed that our notebook tests don't use `pytest-randomly`, so any given run is not reproducible.  While addressing this, I also re-organized the "optional" dependencies a bit.
=> Reorganize optional dependencies, and use randomly in notebook tests

docs/circuit_cutting/how-tos/how_to_generate_exact_sampling_coefficients.ipynb
I'm going to leave this open for a few minutes/hours in case I find any other little adjustments that need made.
=> Tweak formatting and shots count in `how_to_generate_exact_sampling_coefficients.ipynb`

docs/circuit_cutting/explanation/index.rst, docs/circuit_cutting/tutorials/index.rst, releasenotes/notes/gate-cutting-workflow-ebbedbdb1313b258.yaml
- use proper sphinx cross references for tutorials & explanation, to prevent bitrot
- fix a few typos
- prefix function xrefs with dots (see also #216)
=> Tweaks to gate cutting workflow release note

circuit_knitting_toolbox/circuit_cutting/cutting_evaluation.py, test/circuit_cutting/test_cutting_evaluation.py
In the future, we might want the code to behave differently based on whether samplers are identical or merely equivalent.  For instance, perhaps we will want identical samplers to mean that the circuit is evaluated all at once on the hardware, while two equivalent samplers could mean the subcircuits are passed to the backend twice independently (see #220 for details).  For now, since we might want to do this in the future, I believe it makes sense to explicitly disallow it until we figure this out.
I also fixed an unrelated typo in an exception message.
=> Ensure that each sampler passed to `samplers` is unique

circuit_knitting_toolbox/utils/transforms.py, test/circuit_cutting/test_cutting_decomposition.py, test/circuit_cutting/test_cutting_evaluation.py, test/utils/test_transforms.py
Closes #218.  I started by modifying `_separate_instructions_by_partition`, but then I encountered a new error, which led me to modify `_circuit_from_instructions` as well.
The only thing I was a little bit unsure about was whether `qc.qubits[j]` would indeed give me the `j`th qubit, but it seems to work: all tests pass.
As a bonus, each subsystem now has a _single_ quantum register which contains all qubits relevant to it.
=> Fix the workflow if an empty circuit is provided

INSTALL.rst
The installation instructions were thorough and correct, but they needed a facelift, and they needed the PyPI installation added as an option.
I lightly borrowed from the [Qiskit installation instructions](https://qiskit.org/documentation/getting_started.html) for language and flow.
=> Update installation instructions

test/README.md
This file is adapted from the quantum-prototype-template.
I am also working on a "developer guide" for the Sphinx docs, which will link to this and a few other files.
Preview at https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/tox-readme/test/README.md
=> Add documentation of the different tox environments

test/circuit_cutting/test_backwards_compatibility.py, test/conftest.py, tox.ini
This will make sure we don't _accidentally_ break the workflows in the current tutorial notebooks as we tweak the API going forward.  We might deliberately break the original workflow, but this should be an intentional choice, not something we do by accident.
=> Add backwards compatibility tests of 0.2 circuit cutting workflows

.github/workflows/release.yml, pyproject.toml, tools/extremal_dependency_versions.py
This switches from flit_core to [hatchling](https://pypi.org/project/hatchling/) for the build system.  Likewise, it uses [hatch](https://github.com/pypa/hatch) rather than flit in the `release.yml` workflow.
The primary goal here is to enable progress on
- #221
I have not tested the release workflow against the test pypi instance, but everything _looks_ right to me.  If it fails when we do the 0.3.0 release, I am happy to debug.
=> Switch from flit to hatchling build system

circuit_knitting/utils/transforms.py
This fixes mypy when run with the most recent rustworkx release, 0.13.0.  Without this, mypy errors with
```
circuit_knitting/utils/transforms.py:30: error: Module "rustworkx" has no attribute "connected_components"; maybe "BiconnectedComponents"?  [attr-defined]
circuit_knitting/utils/transforms.py:102: error: Need type annotation for "graph"  [var-annotated]
Found 2 errors in 1 file (checked 36 source files)
```
It's not clear to me, though, why these annotations are necessary.  I expect there is a better solution.
=> Fix mypy under rustworkx 0.13.0

.github/workflows/test_latest_versions.yml, README.md, test/forging/test_entanglement_forging_ground_state_solver.py, test/forging/test_entanglement_forging_knitter.py
I realized that the entirety of circuit cutting works on Windows, so we might as well advertise native Windows support and test on it too.
Specific changes in this PR:
- skip tests that require pyscf if it is not available
- add Windows workflow to Actions matrix
- add Windows to README platform badge
=> Enable tests on Windows

circuit_knitting/cutting/qpd/__init__.py
`qpdbasis_from_gate` is listed in `__all__`, but it currently doesn't get exported because it hasn't been imported.  Actually, this manifests in the following error:
```
>>> from circuit_knitting.cutting.qpd import *
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'circuit_knitting.cutting.qpd' has no attribute 'qpdbasis_from_gate'
```
(I'm kind of disappointed that ruff doesn't pick this up for us.)
=> Export `qpdbasis_from_gate` from `qpd` module

.github/workflows/test_development_versions.yml, .github/workflows/test_minimum_versions.yml, tools/extremal-python-dependencies.py
This modifies the `extremal-python-dependencies` script so that it is configured on the command line.  This is one step toward making it a standard script.  Configuration is now provided by command line flags in the CI workflows.
=> Move configuration out of `extremal-python-dependencies`

pyproject.toml, tox.ini
This PR ignores *all warnings* from opflow, which is being prohibitively noisy in our unit tests. It brings our total warnings down from 104 to 14. This would ignore non-deprecation-warnings as well, but since opflow is deprecated and we do not use it directly in our source code, this is an acceptable tradeoff.
This PR also specifies the test path in the new pytest config in `pyproject.toml`, so it no longer needs to be specified in `tox.ini`, so we remove it in tox.
=> Ignore opflow warnings

circuit_knitting/cutting/cutqc/mip_model.py, circuit_knitting/utils/transforms.py, tox.ini
I've also added `circuit_knitting/` to the paths passed to pytest, as this is required for doctests to be discovered.
=> Improve `separate_circuit` docstring

docs/entanglement_forging/how-tos/index.rst
This PR prevents the how-to index in EF from rendering weirdly in the docs. It also brings it more in line with how the other tools' how-to's are indexed
=> Update EF how-to index

circuit_knitting/forging/__init__.py, circuit_knitting/forging/entanglement_forging_ground_state_solver.py, docs/entanglement_forging/how-tos/freeze-orbitals.ipynb, releasenotes/notes/ef-results-bug-5aa84ca5611dd827.yaml, test/forging/test_entanglement_forging_ground_state_solver.py
Resolves #132 
Resolves #247 
This PR fixes a bug which was preventing the EFResults from being properly populated in certain cases, such as when we include `orbitals_to_reduce` argument to `EFGSSolver`
It also introduces an instantiation of the `EFGroundStateSolver` in the bitstring reduction how-to. Users need to pass in the orbitals to reduce here, as well as the ansatz, so that the observable can be properly reduced as well. This has been a point of confusion, so adding this step should clear this confusion up.
=> Fix bug in result creation and add instantiation of EFGSS to how-to

tox.ini
Sometimes I type these.  It'd be nice to have them do the right thing, rather than invoke the default environment.
=> Add `py-notebook` and `py3-notebook` tox environments

circuit_knitting/cutting/qpd/qpd.py, releasenotes/notes/dx-qpd-inst-bug-fe9c50dad716b848.yaml, test/cutting/qpd/test_qpd.py
If `TwoQubitQPDGate` indices are specified out of order in the arguments to `decompose_qpd_instructions`, the  [data_id_offset](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/665196fc9b14f31d620e489e18fb339b33deb895/circuit_knitting/cutting/qpd/qpd.py#L429) variable specified in the function will not work as intended when decomposing those gates, and gates which are not `BaseQPDGate` instances will be treated as QPD gates, causing mysterious index errors.
This PR fixes that bug and implements a unit test to test against this problem.
=> Fix bug in decompose-qpd-instructions

circuit_knitting/cutting/__init__.py, circuit_knitting/cutting/qpd/__init__.py, circuit_knitting/cutting/qpd/qpd.py, releasenotes/notes/supported-gates-d2156f58bc07fc7a.yaml, test/cutting/qpd/test_qpd.py
There should be a central place where users can find out whether or not a gate is supported without using a `try` block and querying `qpdbasis_from_gate`. I've addressed this here with a simple function that returns a hard-coded `set`. I had also considered a function which takes a gate as input and returns a `bool`, but I just think this implementation is better for both the dev and user.
=> Add a supported_gates function

pyproject.toml, releasenotes/notes/explicit-numpy-dependency-fdd89846b37a8d4c.yaml
We are currently relying on numpy being installed as a transitive dependency (through, at the very least, Qiskit Terra).  Even better would be to specific it explicitly, and to set the minimum version following https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/pull/70#issuecomment-1501957148.
=> Add explicit numpy dependency

pyproject.toml
This is similar to #286 in that it adds an explicit dependency on something that we are already importing directly (in this case, rustworkx).  I set the minimum version to 0.12.0 since that is what Qiskit Terra 0.24.0 requires.
=> Add explicit dependency on rustworkx and scipy

circuit_knitting/cutting/qpd/qpd.py, releasenotes/notes/additional-gates-f4ed6c0e8dc3a9be.yaml, test/cutting/qpd/test_qpd.py, test/cutting/test_cutting_roundtrip.py
Ref #288.  I'll fix this up after #290 is merged.
=> Add support for cut `ECRGate`

.github/workflows/docs.yml
This is useful to iterate on docs and debug CI issues.
The artifact will be uploaded to GitHub Actions like this:
=> Upload docs build in CI

docs/conf.py
We have no reason to keep a running enumeration on our figures and/or code snippets, and when `numfig` is set to `True` in `docs/conf.py`, it causes code snippets and figures with captions to have their caption prepended with `Listing #`. We can turn this back on and reckon with captions later if need be, but let's turn it off for now. It clutters the code snippet captions pretty badly
=> don't enumerate figures and code snippets

tox.ini
#307 includes a slow test that also provides important code coverage. I suggest we run slow tests on coverage only. This will allow us to continue to test a higher proportion of our code without bogging down every workflow with slow tests.
=> Run slow tests for coverage only

docs/index.rst
This keeps the same order of docs, but adds section headers so it's more obvious what is what.
It also adds a page to `<self>` so that you can go back to the home page.
Before:
After:
=> Add caption headers to site table of contents

circuit_knitting/utils/observable_grouping.py
`ckt.utils.observable_grouping.ObservableCollection.lookup` docstring intro sentence reads a little vague in the API. Adding a little context to the intro sentence of docstring to make API more clear
=> improve ObservableCollection.lookup docstring

docs/index.rst
I find the new one much easier to scan.
Old:
New:
=> Shorten the section names in the docs

.github/workflows/test_latest_versions.yml, INSTALL.rst, pyproject.toml
There are new cplex binaries for Python 3.11, so we can run all our tests on Python 3.11 now.
Ref https://github.com/qiskit-community/qiskit-optimization/pull/533
=> Cplex is now compatible with Python 3.11

.github/workflows/README.md, .github/workflows/docker.yml, INSTALL.rst, compose.yaml
From https://docs.docker.com/compose/migrate/:
> From July 2023 Compose V1 stopped receiving updates. It’s also no longer available in new releases of Docker Desktop.
>
> [...]
>
> Unlike Compose V1, Compose V2 integrates into the Docker CLI platform and the recommended command-line syntax is `docker compose`.
From https://docs.docker.com/compose/compose-file/03-compose-file/:
> The default path for a Compose file is `compose.yaml` (preferred) or `compose.yml` that is placed in the working directory. Compose also supports `docker-compose.yaml` and `docker-compose.yml` for backwards compatibility of earlier versions.
From https://github.com/compose-spec/compose-spec/blob/master/spec.md:
> The top-level `version` property is defined by the Compose Specification for backward compatibility. …
=> Migrate to Docker Compose V2

circuit_knitting/forging/entanglement_forging_ground_state_solver.py, docs/entanglement_forging/explanation/index.rst, docs/entanglement_forging/how-tos/freeze-orbitals.ipynb
Defer to how-to in explanatory, rather than duplicating the code block in freezing orbs section of explanatory. Add a reference to explanatory in EFGSSolver init docstring for the `orbitals_to_freeze` arg.
=> Update freezing orbitals documentation

docs/conf.py, pyproject.toml
The main changes are:
1. Gets rid of the top Qiskit nav bar.
2. Adds the project name and Qiskit Ecosystem logo to the left sidebar. (You can disable the logo or replace it with your own)
=> Switch to Qiskit Ecosystem theme

Dockerfile
Now that CKT supports Python 3.11, we might as well use the latest version in the Dockerfile.
=> Bump Python version in Dockerfile to 3.11

circuit_knitting/utils/orbital_reduction.py
This fixes the formatting of the example at https://qiskit-extensions.github.io/circuit-knitting-toolbox/stubs/circuit_knitting_toolbox.utils.orbital_reduction.reduce_bitstrings.html#circuit_knitting_toolbox.utils.orbital_reduction.reduce_bitstrings.
I verified this locally.
I plan to merge once tests pass.
=> Fix formatting of example in `reduce_bitstrings` docstring

docs/conf.py, docs/index.rst
This PR does two things to make the repository more discoverable from the Sphinx build
- moves the mention of the GitHub repository to the section titled "Developer guide"
- adds a GitHub icon in the footer of each page, which links to the repo, following the instructions at https://pradyunsg.me/furo/customisation/footer/#using-embedded-svgs
=> Make the repository link more obvious from the Sphinx build

README.md
This is complementary to #338, but in the reverse direction.  I want to make sure the docs are easily discoverable from github if one does not know to look in the sidebar.  I also added a ruff badge for good measure, but I could be convinced this is unnecessary.  Preview at https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/docs-badge/README.md
=> Add README badge linking to stable documentation

pyproject.toml
This adds a dependency on ipykernel, the lack of which caused CI failures in #343 and #344.   https://github.com/jupyter/jupyter-sphinx/pull/226 is my attempt to "fix" this upstream.
=> Fix sphinx build by depending on ipykernel directly

pyproject.toml
black advertises that there should be no breaking changes during a stable version series.  If we merge this, we will reduce some dependabot noise (a few times per year).
Alternative to #343.
=> Pin black's major version only

docs/circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb
This is a follow-up to #174.  In that PR, `partition_problem` was not described, but `execute_experiments` was mistakenly described in two locations.
=> Fix description of `partition_problem` in wire cutting tutorial

circuit_knitting/cutting/cutting_decomposition.py, test/cutting/test_cutting_decomposition.py
I noticed when experimenting with `partition_problem` that it blows up if you give it a circuit that contains an unlabeled `TwoQubitQPDGate`.  In our workflows so far, all `TwoQubitQPDGate`s are created within `partition_problem` itself, as the first thing it does is call `partition_circuit_qubits`, which creates the gates with the labels.  However, it's not strictly necessary for the gates to have labels, and people might want to place some `TwoQubitQPDGates` manually in addition to the ones across the partition labels.  (Also, in the future, we might want to make `partition_labels` optional, at which point it will just partition as well as it can using the `TwoQubitQPDGates` that have been placed.)
I double checked, and the added test indeed fails without the accompanying change.
=> Fix `partition_problem`'s handling of unlabeled `TwoQubitQPDGate`s

test/cutting/test_cutting_roundtrip.py
This is my PR promised at https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/pull/333#pullrequestreview-1577702611.
Essentially, I really want the roundtrip tests to regularly test both experiment workflows: the one that uses a single sampler, and the one that uses multiple samplers.  Of course, all sampler(s) used should be `ExactSampler`s, and the expectation values are required to work out exactly, up to floating point error.
This PR achieves this by flipping a coin each time a roundtrip test is called.
=> Use multiple samplers sometimes in the roundtrip tests

circuit_knitting/cutting/cutting_decomposition.py, circuit_knitting/cutting/qpd/instructions/qpd_gate.py, circuit_knitting/utils/transforms.py, releasenotes/notes/automatic-partition-labels-f90428f66ec5543a.yaml, test/cutting/test_cutting_decomposition.py
... and introduce `TwoQubitQPDGate.from_instruction`.
I've been working on a PR that introduces a how-to for placing single-qubit wire cuts based on #326.  In the course of completing that, I've realized that it would be _very_ nice to have the feature introduced in the current PR, hence its addition to the 0.3 milestone.  Hopefully I can convince you quickly of its value :slightly_smiling_face:.  I'll open the other PR shortly.  It doesn't strictly depend on this, but (as you will see when I do), it becomes much nicer with this.
=> Allow `partition_labels` to be determined automatically in `partition_problem`

docs/circuit_cutting/how-tos/how_to_generate_exact_quasi_dists_from_sampler.ipynb, docs/circuit_cutting/how-tos/how_to_generate_exact_sampling_coefficients.ipynb, docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb, docs/circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb
This modifies our use of `partition_problem` in the documentation to avoid unpacking it like a tuple.  We already know that we plan to break the tuple interface in the v0.4 release cycle.  This prepares for the change, by demonstrating code in our documentation that is resilient to our planned changes.  I'm not sure if `PartitionedCuttingProblem` will end up remaining a `namedtuple` or not; if we add a few more elements to it, it might make more sense for it to be a `dataclass`.  Either way, this code should continue to work on v0.4.  I don't want to _hold_ us to this: if there's some other breaking change we need to make, we should do it.  But this change at least provides some hope that our tutorials from v0.3 might work unmodified on v0.4, too.
=> Avoid unpacking `PartitionedCuttingProblem` in tutorials & how-tos

circuit_knitting/cutting/__init__.py, circuit_knitting/cutting/qpd/__init__.py, circuit_knitting/cutting/qpd/instructions/qpd_gate.py, circuit_knitting/cutting/qpd/qpd.py, circuit_knitting/cutting/qpd/qpd_basis.py, docs/circuit_cutting/how-tos/how_to_generate_exact_sampling_coefficients.ipynb, releasenotes/notes/qpd_basis_from_instruction-6f46489c395ba20b.yaml, test/cutting/qpd/test_qpd.py, test/cutting/qpd/test_qpd_basis.py, test/cutting/test_cutting_decomposition.py, test/cutting/test_cutting_workflows.py
This renames `QPDBasis.from_gate()` to `QPDBasis.from_instruction()`.  As of v0.3, the name `from_gate` is no longer appropriate, since the function supports `Move`, which is an `Instruction` but not a `Gate`.  Being that #367 introduced `TwoQubitQPDGate.from_instruction()`, I felt that now is the time to also rename `QPDBasis.from_instruction()` for consistency, so users aren't always confused about which calls it `from_gate` and which calls it `from_instruction`.
I left the argument name as `gate` in some places to reduce the needed size of the diff, but I did mark these places as position-only arguments in the new interface, so that the name can be changed later.
I have also renamed `qpdbasis_from_gate` -> `qpdbasis_from_instruction`, but I left this out of the release note because …
=> Rename `QPDBasis.from_gate()` to `QPDBasis.from_instruction()`

docs/circuit_cutting/how-tos/README.rst, docs/circuit_cutting/how-tos/index.rst, docs/circuit_cutting/tutorials/index.rst
I noticed that the cutting tutorials & how-tos are double nested in the [table of contents](https://qiskit-extensions.github.io/circuit-knitting-toolbox/#contents).  This currently happens because each header appears redundantly, in `README.rst` and `index.rst`.  This PR fixes the redundancy by removing headers from `index.rst`.  They are worth keeping in `README.rst`, because there they will be shown to users who browse to those directories on github.com.
I built the docs locally, and they look great with this change.
=> Fix double-nesting of cutting tutorials & how-tos in table of contents

.github/workflows/test_development_versions.yml, pyproject.toml, releasenotes/notes/qiskit-metapackage-e755916a18b4c62c.yaml, tools/extremal-python-dependencies.py
This is an alternative to #386, in an attempt to get the "development version tests" to _actually_ use the development version of Qiskit.
=> Fix fallout from Qiskit metapackage migration

test/cutting/test_backwards_compatibility.py
This adds to the tests a slightly modified version of the v0.3 tutorials, in order to test backwards compatibility of the workflow.  My hope is that these can continue to work when we release v0.4, but if we think of a good reason that they need to break between now and then, we can remove them.
=> Add "backwards compatibility" tests based on v0.3 tutorials

.github/workflows/test_development_versions.yml
=> Temporarily remove Qiskit Nature from dev version tests

README.md
I just can't stop messing with the badges.
The PR adds a "Release" badge, which shows the latest pypi release version and links to the release page on GitHub.
I've also modified the "Python" badge to get the supported versions automatically from pypi.  This will show the versions supported by the latest _released_ of CKT version, rather than by `main`.  However, I think this is probably what users will actually be the most interested in: what versions are supported if I run `pip install`, right now?
Preview at https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/release-badge/README.md
=> Add a release badge

circuit_knitting/cutting/cutting_experiments.py, test/cutting/test_cutting_experiments.py
I noticed that `generate_cutting_experiments` really returns _coefficients_, not weights.  While weights (e.g., as returned by `generate_qpd_weights`) are all positive and can be rescaled arbitrarily, coefficients can be either positive or negative and cannot be rescaled arbitrarily.  (Actually, the difference between weights and coefficients deserves some explanation, see #411.)
The misleading jump from "coefficients" to `weights` is in the following snippet:
https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/f33317fde7de9f2c6a5c8916ff301a5388e3eedb/circuit_knitting/cutting/cutting_experiments.py#L144-L145
Interestingly, this was already labeled `coefficients` at the call site in `cutting_experiments.py`.
https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/f …
=> `generate_cutting_experiments` returns coefficients, not weights

circuit_knitting/cutting/cutting_decomposition.py, circuit_knitting/cutting/cutting_evaluation.py, circuit_knitting/cutting/cutting_experiments.py, circuit_knitting/cutting/cutting_reconstruction.py, test/cutting/test_cutting_workflows.py
Fixes #390
I'm leaning against adding a release note, because I don't see any reason to draw attention to this.  This is mostly a conceptual cleanup.
=> Make the cutting workflow work with any `Hashable` as label

circuit_knitting/cutting/cutting_experiments.py, circuit_knitting/cutting/cutting_reconstruction.py
This is something that pylint should have caught if we were using it (#146).  This way, the tracebacks will say
> The above exception was the direct cause of the following exception:
rather than
> During handling of the above exception, another exception occurred:
=> Use "raise from" in `except` blocks

circuit_knitting/cutting/cutting_decomposition.py, circuit_knitting/cutting/cutting_evaluation.py, docs/circuit_cutting/how-tos/how_to_generate_exact_quasi_dists_from_sampler.ipynb, docs/circuit_cutting/how-tos/how_to_generate_exact_sampling_coefficients.ipynb, docs/circuit_cutting/how-tos/how_to_specify_cut_wires.ipynb, releasenotes/notes/deprecate-execute_experiments-b96e39653546dcc1.yaml, test/cutting/test_cutting_decomposition.py, test/cutting/test_cutting_evaluation.py, test/cutting/test_cutting_roundtrip.py, test/cutting/test_cutting_workflows.py
Fixes #405.
The last sentence in this PR's release note will become true as soon as #404 is merged.
Remaining action items
=> Deprecate `execute_experiments()`

circuit_knitting/forging/entanglement_forging_knitter.py, circuit_knitting/utils/simulation.py, docs/circuit_cutting/cutqc/tutorials/tutorial_1_automatic_cut_finding.ipynb, docs/circuit_cutting/cutqc/tutorials/tutorial_3_cutting_with_quantum_serverless.ipynb
This migrates from `bind_parameters` to `assign_parameters`, as `bind_parameters` has been deprecated (https://github.com/Qiskit/qiskit/pull/10792)
=> Migrate from `bind_parameters` to `assign_parameters`

.mergify.yml
This PR configures mergify to perform stable backports for us when we add the "stable backport potential" label to a pull request.  This is essentially the same as [the configuration that qiskit-optimization uses](https://github.com/qiskit-community/qiskit-optimization/blob/main/.mergify.yml), except I removed everything regarding "automerge" and the merge queue.  We seem to get by just fine without a merge queue, and if we _do_ decide to use one, we might as well use GitHub's.
Until now, I've been running `git cherry-pick` manually to backport things to the `stable/*` branches, but using mergify instead will provide mode transparency and opportunities to get involved in the process -- and enforce that tests actually pass before changes are committed to the stable branch.
One potential …
=> Configure mergify to perform stable backports

circuit_knitting/cutting/qpd/qpd.py, test/cutting/qpd/test_qpd.py, test/cutting/qpd/test_qpd_basis.py
Now that Qiskit [supports singleton gates](https://github.com/Qiskit/qiskit/pull/10314) for non-controlled, parameterless gates, we might as well use parameterless gates in each place possible to take advantage of this.
=> Use parameterless gates where possible

circuit_knitting/cutting/cutting_experiments.py, circuit_knitting/cutting/qpd/qpd.py, test/cutting/qpd/test_qpd_basis.py
While reading the OpenQASM 3 paper (page 24 of https://arxiv.org/abs/2104.14722v2), I noticed that there is actually a way to rotate to the Y basis to the Z basis in a single parameterless gate.  We might as well use that (most efficient) method here before it gets repeated many times after we generate many subexperiments.
=> Use single gate (`SXGate`) to rotate from Z to Y measurement basis

pyproject.toml
https://github.com/pyscf/pyscf/issues/1783 has now been resolved in a pyscf release, so we no longer have a restriction on scipy.
=> Remove upper version bound on scipy

circuit_knitting/cutting/cutqc/wire_cutting.py, circuit_knitting/cutting/qpd/qpd.py, circuit_knitting/utils/simulation.py, docs/circuit_cutting/cutqc/tutorials/tutorial_3_cutting_with_quantum_serverless.ipynb, tox.ini
Closes #319.
I changed CutQC's `_print_cutter_result` to display `num_cuts` as well (previously, it ignored it).  In passing, I also removed the `num_subcircuit` argument to this function, as it was redundant with `len(subcircuits)`.
In other files, I prefixed intentionally ignored arguments with `unused_` or `ignored_` so pylint will ignore them.
=> Enable pylint's `unused-argument` check

circuit_knitting/cutting/cutting_experiments.py, circuit_knitting/cutting/cutting_reconstruction.py, circuit_knitting/forging/cholesky_decomposition.py
Since these sums start with 0, they should end with $N-1$; else, there are $N+1$ terms.  Even though we don't explicitly define `N` or `M`, it is most natural for `N` to represent the number of observables or Cholesky operators, rather than have it be one off from that number.
=> Don't overcount expanded sum terms in documentation

pyproject.toml, releasenotes/notes/qiskit-nature-pinned-c359e3933bfef993.yaml
Until #408 is merged (and #406 is thus fixed), we know that CKT will not work with Qiskit Nature 0.7 (a release that is expected some time soon).  We might as well preemptively mark our CKT releases until #408 is merged as being incompatible with Qiskit Nature 0.7.  Otherwise, users might be unpleasantly surprised once Qiskit Nature 0.7 is released and entanglement forging no longer works.
As an alternative, we _could_ just prioritize getting #408 in shape to merge, but there's no harm in having this pinned until that happens.
TODO
=> Temporarily pin qiskit-nature < 0.7

test/cutting/test_cutting_roundtrip.py, test/cutting/test_cutting_workflows.py
- remove an outdated docstring comment
- `simuated_expvals` -> `reconstructed_expvals` for consistency with tutorials
- remove unnecessary circuit copy
- fix typo
=> Clean up roundtrip tests

circuit_knitting/cutting/cutting_evaluation.py, circuit_knitting/cutting/cutting_experiments.py, circuit_knitting/cutting/cutting_reconstruction.py, circuit_knitting/cutting/qpd/qpd.py, docs/circuit_cutting/how-tos/how_to_specify_cut_wires.ipynb, docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb, docs/circuit_cutting/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb, docs/circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb, releasenotes/notes/register_order_swapped-5b07fb661c6250f9.yaml, test/cutting/test_cutting_evaluation.py, test/cutting/test_cutting_experiments.py, test/cutting/test_cutting_reconstruction.py, test/cutting/test_cutting_roundtrip.py, test/cutting/test_cutting_workflows.py
This swaps the order of the registers such that `qpd_measurements` now comes last.  The motivation here is two-fold:
1. To be consistent with the natural register order when reconstructing probability distributions (#428)
2. To remove the need to pass around `num_qpd_bits`
=> Swap register order, removing need to pass `num_qpd_bits`

circuit_knitting/forging/entanglement_forging_ground_state_solver.py, docs/entanglement_forging/tutorials/tutorial_1_getting_started.ipynb, docs/entanglement_forging/tutorials/tutorial_2_forging_with_quantum_serverless.ipynb, pyproject.toml, releasenotes/notes/qiskit-algorithms-ec3fe782619bab45.yaml, test/forging/test_entanglement_forging_ground_state_solver.py
The `qiskit.algorithms` module was deprecated in Qiskit Terra 0.25, which was released on July 27.  This updates the code to use the `qiskit-algorithms` package instead, to ensure compatibility with future Qiskit versions.
=> Migrate from `qiskit.algorithms` to `qiskit-algorithms` package

docs/entanglement_forging/how-tos/specify-problem.rst
This was overlooked in #83.  It is now causing CI errors in the docs workflow (see #448), now that a Qiskit version without `PauliTable` has been released.
=> Update forging how-to to Qiskit Nature 0.5

.github/workflows/test_development_versions.yml
Following https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/issues/406#issuecomment-1807252032
=> Remove qiskit `main` from "developments versions" CI workflow

pyproject.toml
This fixes the notebook tests (and CI).  See discussion at #453.
=> Pin `aiohttp != 3.9.0` during notebook tests

pyproject.toml
In #454, I pinned `aiohttp`, but the failure was actually due to `async-timeout` not being installed
(https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/issues/453#issuecomment-1819548746).
This PR updates `pyproject.toml` in accordance with this root cause.
We can remove this line once a version of ray is released that fixes https://github.com/ray-project/ray/issues/41267.
=> Install `async-timeout` rather than pin `aiohttp`

circuit_knitting/cutting/cutting_experiments.py, circuit_knitting/utils/__init__.py, circuit_knitting/utils/transpiler_passes.py, releasenotes/notes/remove-redundant-resets-1893a61a341e6ce8.yaml, test/cutting/test_cutting_workflows.py, test/utils/test_transpiler_passes.py
Fixes #452.
I'd still like to swap the tutorial and how-to as suggested in the second point at https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/issues/452#issue-1991864801, but this can be done independently in a follow-up PR.
=> Remove unnecessary resets in `generate_cutting_experiments`

test/cutting/test_cutting_decomposition.py, test/cutting/test_cutting_evaluation.py, test/utils/test_transforms.py
Namely, the `toffoli` and `cnot` methods have been deprecated starting with Qiskit 0.45 and should be replaced with `ccx` and `cx`, respectively.
=> Migrate away from deprecated `QuantumCircuit` methods

pyproject.toml
This will need to wait until Ray 2.9.0 is released, following https://github.com/ray-project/ray/issues/41267#issuecomment-1819909717.
Fixes #453.
=> Remove `async-timeout` from notebook dependencies

docs/circuit_cutting/tutorials/README.rst
The Qiskit Runtime doesn't behave well when you use primitives in parallel. The CKT tutorials which ran the circuit batches in parallel would randomly, and rather frequently, hang indefinitely. We never tracked down the cause, but we suspected the primitives were just not thread safe.
We removed the parallelization from the tutorials, but we did not update the description of tutorial 1 to reflect that. This PR updates that description.
=> Update description of cutting tut 1

.ruff.toml
`ruff` wants us to use the `lint` package in these two spots. This PR just removes a couple of warnings from our `lint` CI job
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `.ruff.toml`:
- 'ignore' -> 'lint.ignore'
- 'per-file-ignores' -> 'lint.per-file-ignores'
```
=> Update ruff config

.github/workflows/test_development_versions.yml, pyproject.toml, releasenotes/notes/remove-forging-340dc643092a747a.yaml
qiskit-algorithms is no longer needed as a dependency now that entanglement forging is gone.
This is a follow up to #479.
=> Drop dependency on qiskit-algorithms

CONTRIBUTING.md, README.md, docs/circuit_cutting/cutqc/tutorials/tutorial_1_automatic_cut_finding.ipynb, docs/circuit_cutting/cutqc/tutorials/tutorial_2_manual_cutting.ipynb, docs/conf.py, docs/index.rst, releasenotes/notes/0.1/migrate-to-qiskit-nature-0.5.0-96e90cd48f36d731.yaml
These links were all working okay thanks to redirects. But it's better to use the correct link directly.
=> Remove qiskit.org links

.github/workflows/test_development_versions.yml
This changes the development version tests to test against qiskit `main` (the development version) rather than `stable/1.0` (which is currently the stable version, but will not always be).  This was part of #408, which got closed out in favor of #479.
=> Dev tests should test against qiskit `main`, not stable branch

README.md, circuit_knitting/cutting/cutting_reconstruction.py, pyproject.toml, releasenotes/notes/bump-dependency-versions-d5dc3b10ba842f2d.yaml, releasenotes/notes/cutting-samplerv2-603b0c631a3330df.yaml, test/cutting/test_cutting_reconstruction.py, test/cutting/test_cutting_workflows.py
Fixes #488.
This ~~is waiting on~~ requires one of the following before we can move forward (EDIT: the first item is now done!).
- Qiskit fix to https://github.com/Qiskit/qiskit/issues/12043
- Qiskit Aer release containing https://github.com/Qiskit/qiskit-aer/issues/2078
To-do list:
=> Add support for `SamplerV2`

tox.ini
This should help with tracking down the intermittent CI failures in the notebook tests.
I will merge this as soon as CI passes.
=> Lower the nbmake cell timeout to 5 minutes

circuit_knitting/cutting/cutqc/wire_cutting_evaluation.py, docs/circuit_cutting/cutqc/tutorials/tutorial_1_automatic_cut_finding.ipynb, docs/circuit_cutting/cutqc/tutorials/tutorial_2_manual_cutting.ipynb
Fixes #501.
I've also replaced `service_args`, which appears nowhere else in the repository, with `service`, in the notebooks.
Unfortunately, even with this change, I see the following error when I try to run the first tutorial notebook on a hardware backend:
```
File ~/circuit-knitting-toolbox/circuit_knitting/cutting/cutqc/wire_cutting_evaluation.py:236, in run_subcircuits_using_sampler(subcircuits, sampler)
234 for i, qd in enumerate(quasi_dists):
235     probabilities = qd.nearest_probability_distribution()
--> 236     probabilities_out = np.zeros(2 ** subcircuits[i].num_qubits, dtype=float)
238     for state in probabilities:
239         probabilities_out[state] = probabilities[state]
ValueError: Maximum allowed dimension exceeded
```
I think this may be unrelated to the ISA change, …
=> Add transpilation to cutqc evaluation

test/cutting/cut_finding/test_cco_utils.py
Follow up to https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/pull/520#discussion_r1544626447
These are still not _fixtures_, but at least they will only be run if the test is executed.
=> Construct test circuits in functions, not module

docs/index.rst
If I end up at a software package's docs page before their Github repo, it is nice to be able to get directly to the Github repo from there. I find github repos can often be more difficult to find on search engines than docs pages
We have a small button which shows our stars and links users to Github. I think that is great, and I think we can also just add a button to our toolbar that takes people there.
This is personal preference, but this is something I personally think is worth having if your homescreen toolbar isn't already crowded
=> Add github button to docs homepage

pyproject.toml, tox.ini
This removes the super-long lines for `tox.ini`, and prepares us to enable some additional rules.
This seems like a no-brainer, so I plan to merge this as soon as CI passes.
=> Move pylint configuration to `pyproject.toml`

docs/conf.py, tox.ini
Currently, we have set `nbsphinx_execute = "auto"` in the Sphinx configuration so that [notebooks are _not_ re-executed](https://nbsphinx.readthedocs.io/en/0.9.3/never-execute.html) anytime someone runs `tox -e docs`, in large part to speed up the build cycle for quick development.
However, even without changing this for local builds, we have the option of changing this on CI, which is where our deployed documentation is built.
Here's what would be different:
- The notebooks in the docs will always be the result of a fresh run, so we will no longer to be forced to manually re-execute notebooks e.g., anytime the Qiskit default visualizaions change (#524) or  when deprecation warnings are added to our own codebase (possible part of #533), etc.
- We will have less control about what output …
=> RFC: Re-execute notebooks on CI when building Sphinx docs

circuit_knitting/cutting/qpd/decompositions.py
This is a follow-up to the conversation at https://github.com/Qiskit/qiskit/pull/11635#issuecomment-1915535406.
The toplevel package import was made available in https://github.com/Qiskit/qiskit/pull/11687 in time for Qiskit 1.0.
I plan to merge once CI passes.
=> Fix hyper-specific import of `qiskit.synthesis.TwoQubitWeylDecomposition`

circuit_knitting/cutting/cut_finding/circuit_interface.py, circuit_knitting/cutting/cut_finding/cut_optimization.py, circuit_knitting/cutting/cut_finding/lo_cuts_optimizer.py, pyproject.toml, test/cutting/cut_finding/test_circuit_interfaces.py
When I ran pylint in its default configuration, I noticed a few `dangerous-default-value` warnings in the new cut finder.  I think it's worth adding this to our pylint configuration and fixing the existing issues in the code base.  (Even though users aren't supposed to directly call this code, adding this to our config allows us to prevent similar dangerous defaults in places we _do_ care about.)
=> Enable pylint's `dangerous-default-value` check

docs/circuit_cutting/cutqc/index.rst, docs/circuit_cutting/cutqc/tutorials/tutorial_1_automatic_cut_finding.ipynb, docs/circuit_cutting/cutqc/tutorials/tutorial_2_manual_cutting.ipynb
This is a follow-up to #527.  Marking as a draft because it might be worth putting other updates of places we missed as we discover them.
=> Update cutqc tutorials index with deprecated status

.github/workflows/test_latest_versions.yml
cplex, which is required by cutqc, is not available on ARM
=> Switch to `macos-13` runner so it is an Intel chip

.github/workflows/docs.yml, .github/workflows/lint.yml
This reverts commit 0d9cb60e7316f9a1ab6d92a11d6c2c8b6134351c (#559).
I believe the temporary workaround is no longer needed.
=> Revert "Temporarily disable worktrees in docs and lint workflows (#559)"

circuit_knitting/cutting/cutting_experiments.py, test/cutting/test_cutting_experiments.py
=> Early terminate from loops when generating cutting experiments

circuit_knitting/cutting/qpd/decompose.py, releasenotes/notes/nonzero-register-size-e112e34417ff79b9.yaml, test/cutting/qpd/test_qpd.py
Fixes #564 
This is a potential workaround to https://github.com/openqasm/qe-qasm/issues/37
=> Force at least one classical bit in `qpd_measurements` register

README.md, docs/index.rst
=> Remove discussion about user's compute env from knitting docs

CITATION.bib, docs/index.rst
I've removed the authors who contributed solely to forging and added a few authors who have contributed to circuit knitting.  I also updated the documentation to encourage users of forging to use an older version of the citation.
It's worth triple checking this to make sure there are no errors.
Closes #375.
=> Update authors in `CITATION.bib`

CITATION.bib
This is a follow up to #580.  This removes six additional authors who only contributed to entanglement forging and have made no direct contributions to circuit cutting to the best of my knowledge.
I've also reformatted with one author per line.
A diff that ignores whitespace can be generated by running `git show --color-words` on this branch.
=> Update `CITATION.bib` to remove entanglement forging authors

.github/workflows/test_latest_versions.yml
~~This is due to python 3.8 no longer being available on the macos-latest CI runner.~~
This ~also~ allows us to now perform CI on ARM chips on macOS.
This also restores the ubuntu minimum version to 3.8 so that we test on 3.8 somewhere. https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/issues/515#issuecomment-2073378582
~~We might see intermittent CI failures again until #556 is merged (expected to be very soon).~~
=> Test on ARM macOS runners

.github/workflows/coverage.yml
It looks like we no longer even need to coveragepy-lcov tool: https://github.com/nedbat/coveragepy/issues/587#issuecomment-1019370754
=> Fix coverage workflow and remove workflow dependency on coveragepy-lcov

pyproject.toml
This is no longer necessary now that a release has been made which includes https://github.com/jupyter/jupyter-sphinx/pull/226.
This PR reverts #345.
=> Remove explicit dependency on ipykernel

docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb, docs/circuit_cutting/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb, docs/circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb
This fixes a typo and splits the cell so that the results are retrieved in their own cell.  This is nice because then the user will have a cell complete once all jobs are submitted and another complete when all results are available.  I also removed an outdated reference to the old "commented block."
=> Tutorials: Fix typo and split cell that retrieves results

circuit_knitting/utils/bitwise.py, tox.ini
This restriction was previously necessary, but it no longer appears to be, as far as I can tell.
Getting rid of the restriction will make these environments work on systems where `python3.10` is not installed.
=> Remove `basepython` restriction in `lint` and `coverage` environments

circuit_knitting/cutting/automated_cut_finding.py
Add explanation for the fields in `OptimizationParameters`, in particular `max_gamma` and `max_backjumps`.
=> Describe optimization parameters in docs

circuit_knitting/utils/transforms.py
More info at https://github.com/Qiskit/qiskit/issues/12581
=> transforms.py: Avoid setting the barrier to be a uuid object

README.md, docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb, docs/circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb, pyproject.toml, releasenotes/notes/bump-dependency-versions-26e93b55695c3034.yaml
This is necessary to prevent a `DeprecationWarning` under qiskit-ibm-runtime 0.24, which is currently visible in the [first](https://qiskit-extensions.github.io/circuit-knitting-toolbox/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.html) and third tutorials.  The warning is a result of the merging of https://github.com/Qiskit/qiskit-ibm-runtime/pull/1584.
qiskit-ibm-runtime 0.24 depends on qiskit>=1.1, so I had to bump the qiskit version as well.
Technically, this version bump is only required by the notebooks, not the actual CKT library, but the "minimum version tests" aren't equipped to deal with situations where the notebooks have a different minimum version than the CKT library.
=> Bump qiskit-ibm-runtime version and use `mode=batch`

.github/workflows/test_minimum_versions.yml, docs/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb, docs/circuit_cutting/tutorials/03_wire_cutting_via_move_instruction.ipynb
This is a stable backport of #623.
This change is necessary to prevent a `DeprecationWarning` under qiskit-ibm-runtime 0.24, which is currently visible in the [first](https://qiskit-extensions.github.io/circuit-knitting-toolbox/circuit_cutting/tutorials/01_gate_cutting_to_reduce_circuit_width.html) and third tutorials and is due to the merging of https://github.com/Qiskit/qiskit-ibm-runtime/pull/1584.
This means that the notebooks now depend on qiskit-ibm-runtime 0.24, which depends on qiskit>=1.1.
The "minimum version tests" aren't equipped to deal with situations where the notebooks have a different minimum version than the library.  For this reason I've disabled the "minimum version tests" on the current stable branch going forward for the notebooks only. I don't want to bump the …
=> Bump qiskit-ibm-runtime version and use `mode=batch` (backport #623)

pyproject.toml
From the looks of the CI failure, DOCplex is incompatible with numpy 2.0.  So, as a way to make the CutQC code continue to work, I am pinning to `numpy <2` on the `stable/0.7` branch.  (CutQC has already been removed from `main`, in #605.)
=> Pin numpy<2 on stable branch

docs/circuit_cutting/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb, test/cutting/test_cutting_workflows.py
This fixes a deprecation warning.
Fixes #632.
=> Pass `backend` as positional argument to `SamplerV2` for job mode

pyproject.toml
We pin most of our linters, but we have gotten away so far without pinning ruff.  However, today CI is broken because the ruff 0.5.2 (patchlevel) release seems to have added a rule.  (Or maybe it fixed a rule that was broken before.  Either way, it broke us.)
From here forward, let's pin ruff, too, and dependabot can propose updating the version from time to time, just as it does with the other linters.
=> Pin `ruff==0.5.1`

pyproject.toml, releasenotes/notes/0.7/prepare-0.7.3-86eeb02864cf60b0.yaml
As the release note explains, we must make a release before August 15 (when Qiskit 1.2 [is due to be released](https://github.com/Qiskit/qiskit/milestone/50)).  Also, a fresh install of CutQC is broken unless a user knows to pin `numpy<2` themself until we cut this release, so we might as well make a patchlevel release sooner rather than later.
Remaining action items (checklist for patchlevel release):
1. `git checkout stable/0.7`
2. `git pull`
3. `git show` (verify it's the commit we want to tag)
4. `git tag -a 0.7.3 -m "Circuit Knitting Toolbox 0.7.3"`
5. `git show` (double/triple check the tag is on the correct branch)
6. `git push origin 0.7.3`
Previous patchlevel release PR: #590
=> Prepare 0.7.3 release

test/cutting/test_cutting_roundtrip.py, test/cutting/test_cutting_workflows.py
=> Use Aer's SamplerV2 instead of SamplerV1

test/cutting/test_cutting_roundtrip.py
=> Migrate to `EstimatorV2` in tests

.github/workflows/test_development_versions.yml, .github/workflows/test_latest_versions.yml, .github/workflows/test_minimum_versions.yml
This started off as part of #648, but it is conceptually an independent change, so I am splitting it off into its own commit.
=> Fix CI workflows to work with development versions of Python

docs/circuit_cutting/explanation/index.rst
Correct the $\theta$ parameter in the explanatory [material ](https://qiskit-extensions.github.io/circuit-knitting-toolbox/circuit_cutting/explanation/index.html#equation-eq-qpd)but replacing it with $-\theta/2$.
=> Edit cutting explanation

.github/workflows/test_development_versions.yml, pyproject.toml
PrimitivesV1 was dropped from qiskit-ibm-runtime 0.28, but we need them to run the cutqc tutorials.
NOTE: this is a PR to the `stable/0.7` branch only to fix the CI failure in #658.
=> Pin qiskit-ibm-runtime when running notebooks

circuit_knitting/cutting/instructions/cut_wire.py, circuit_knitting/cutting/instructions/move.py, circuit_knitting/cutting/qpd/instructions/qpd_gate.py, circuit_knitting/cutting/qpd/instructions/qpd_measure.py, circuit_knitting/cutting/wire_cutting_transforms.py, docs/conf.py, test/cutting/test_wire_cutting_transforms.py
Most CKT copyright headers say "This code is a Qiskit project." ... but a few stragglers say "This code is part of Qiskit."  This PR updates those stragglers.
=> Make project's relationship with Qiskit consistent in the copyright headers

.github/workflows/test_development_versions.yml, .github/workflows/test_minimum_versions.yml, tools/extremal-python-dependencies/README.md, tools/extremal-python-dependencies/extremal_python_dependencies/__init__.py, tools/extremal-python-dependencies/extremal_python_dependencies/main.py, tools/extremal-python-dependencies/pyproject.toml
With this, extremal-python-dependencies can be installed from another package's CI script.  Hopefully this will be a step toward allowing us to avoid some code duplication across repositories.
=> Split `extremal-python-dependencies` out into its own subpackage

docs/conf.py
We might as well do this, to make sure it is set properly.
And it fixes an instance of don't-repeat-yourself.
=> Use `qiskit_addon_cutting.__version__` in `docs/conf.py`

.github/workflows/citation.yml
Previously we were using bash's prefix removal feature to remove the `prototype-` in each repository name to arrive at the desired citation name.  This is not necessary in this repository and others we plan to make in the future, so I am removing it from this workflow.  Now just the repository name itself is appropriate.
Thanks, @caleb-johnson, for noticing this was out of date.
=> Remove "prototype" handling from `citation.yml` workflow

README.md, circuit_knitting/__init__.py, circuit_knitting/cutting/__init__.py, circuit_knitting/utils/__init__.py, releasenotes/notes/renamed-and-deprecated-ee0f28ea333051a5.yaml
=> Deprecate CKT in favor of qiskit-addon-cutting

README.md
There are also more mentions of `Qiskit-Extensions/circuit-knitting-toolbox` in some old release notes but I did not address those yet.
Those links appear to be direct github links to jupyter notebooks rather than links pointing to their HTML rendered versions. Might be a bit more involved to address.
=> fix: broken link in Release shield

docs/how-tos/how_to_specify_cut_wires.ipynb, docs/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb, docs/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb, docs/tutorials/03_wire_cutting_via_move_instruction.ipynb, docs/tutorials/04_automatic_cut_finding.ipynb
=> Phrase tutorials as Qiskit patterns

qiskit_addon_cutting/instructions/move.py, releasenotes/notes/0.2/gate-cutting-workflow-ebbedbdb1313b258.yaml, releasenotes/notes/0.5/deprecate-execute_experiments-b96e39653546dcc1.yaml, releasenotes/notes/0.7/cutting-samplerv2-603b0c631a3330df.yaml, releasenotes/notes/0.7/prepare-0.7.0-48b344ae77523c34.yaml
Relative links to non-API docs will break when migrating to docs.quantum.ibm.com. They should instead be absolute links.
There are also two links to docs.quantum.ibm.com/api/migration-guides. That was migrated from `/api/migration-guides` to `/migration-guides`. While there's a redirect, we should use the new URL directly.
=> Prepare API docs links for ibm.com migration

docs/conf.py, pyproject.toml, qiskit_addon_cutting/__init__.py, qiskit_addon_cutting/cut_finding/cutting_actions.py, qiskit_addon_cutting/cut_finding/lo_cuts_optimizer.py, qiskit_addon_cutting/cutting_decomposition.py, qiskit_addon_cutting/cutting_experiments.py, qiskit_addon_cutting/cutting_reconstruction.py, qiskit_addon_cutting/qpd/decompose.py, qiskit_addon_cutting/qpd/decompositions.py, qiskit_addon_cutting/qpd/instructions/qpd_gate.py, qiskit_addon_cutting/qpd/qpd_basis.py, qiskit_addon_cutting/qpd/weights.py, qiskit_addon_cutting/utils/__init__.py, qiskit_addon_cutting/utils/bitwise.py, qiskit_addon_cutting/utils/iteration.py, qiskit_addon_cutting/utils/observable_grouping.py, qiskit_addon_cutting/utils/simulation.py, qiskit_addon_cutting/utils/transforms.py, qiskit_addon_cutting/utils/transpiler_passes.py, tox.ini
Pydocstyle was deprecated in favor of Ruff. Ruff has the exact same lints via the D ruleset.
As before, we only run the doc checks on source code and not tests.
=> Replace pydocstyle with Ruff

releasenotes/notes/0.2/gate-cutting-workflow-ebbedbdb1313b258.yaml, releasenotes/notes/0.3/two-qubit-wire-cutting-27aff379403ea226.yaml
These were missed in https://github.com/Qiskit/qiskit-addon-cutting/pull/693.
=> Fix two more API links to non-API docs

qiskit_addon_cutting/utils/simulation.py, releasenotes/notes/0.2/gate-cutting-workflow-ebbedbdb1313b258.yaml, releasenotes/notes/0.7/deprecate-cutqc-7541c514bd96fb05.yaml
These were caught by the qiskit/documentation external link checker.
=> Fix broken external docs links

docs/apidocs/index.rst, docs/apidocs/qiskit_addon_cutting.instructions.rst, docs/apidocs/qiskit_addon_cutting.qpd.rst, docs/apidocs/qiskit_addon_cutting.rst, docs/apidocs/qiskit_addon_cutting.utils.bitwise.rst, docs/apidocs/qiskit_addon_cutting.utils.iteration.rst, docs/apidocs/qiskit_addon_cutting.utils.observable_grouping.rst, docs/apidocs/qiskit_addon_cutting.utils.simulation.rst, docs/apidocs/qiskit_addon_cutting.utils.transforms.rst, docs/apidocs/qiskit_addon_cutting.utils.transpiler_passes.rst, docs/conf.py, qiskit_addon_cutting/__init__.py, qiskit_addon_cutting/cut_finding/__init__.py, qiskit_addon_cutting/instructions/__init__.py, qiskit_addon_cutting/qpd/__init__.py, qiskit_addon_cutting/qpd/instructions/__init__.py, qiskit_addon_cutting/utils/__init__.py, qiskit_addon_cutting/utils/bitwise.py, qiskit_addon_cutting/utils/iteration.py, qiskit_addon_cutting/utils/observable_grouping.py, qiskit_addon_cutting/utils/simulation.py, qiskit_addon_cutting/utils/transforms.py, qiskit_addon_cutting/utils/transpiler_passes.py
Applies changes similar to https://github.com/Qiskit/qiskit-addon-obp/pull/24. Refer to that for more explanation.
This repository is laid out a little differently than how qiskit-addon-obp was, however. This repository was extremely flat: all interfaces were explicitly listed in `index.rst` and there were no module pages. Naturally, no functions/classes were inlined on module pages.
Now, the docs are organized by the distinct modules.
<details><summary>new left ToC for docs.quantum.ibm.com</summary>
</details>
=> Reorganize API docs

qiskit_addon_cutting/qpd/decompositions.py, qiskit_addon_cutting/utils/observable_grouping.py, test/qpd/test_qpd_basis.py
The qiskit/documentation external link checker did not like a link to qiskit-terra, which is now qiskit. While it redirects fine, we intentionally try to avoid linking to redirects.
=> Update some Qiskit Terra links to Qiskit repo

pyproject.toml, releasenotes/notes/no-qiskit-1.3.0-8acc5be0edb2f43a.yaml
See discussion in #714.  This will fix CI, and we might as well disallow installing a version of Qiskit that is known to fail CI. By the time this change makes it to a release, the 1.3.1 release will likely be out, so this will be an insignificant restriction by then.
=> Disallow Qiskit 1.3.0

.github/workflows/test_development_versions.yml
This reverts commit 30b158f61fdaa2ab8782d5fe8992247e56ad3f63 (PR #719).
Closes #714 (once CI passes due to https://github.com/Qiskit/qiskit/issues/13504 being fixed).
=> Revert disabling of the second tutorial on dev version CI

pyproject.toml
Somehow, with numpy 2.2, the mypy fails with the following error:
```
qiskit_addon_cutting/cut_finding/circuit_interface.py:318: error: No overload variant of "__getitem__" of "Sequence" matches argument type "signedinteger[_32Bit | _64Bit]"  [call-overload]
qiskit_addon_cutting/cut_finding/circuit_interface.py:318: note: Possible overload variants:
qiskit_addon_cutting/cut_finding/circuit_interface.py:318: note:     def __getitem__(self, int, /) -> int | tuple[str, int]
qiskit_addon_cutting/cut_finding/circuit_interface.py:318: note:     def __getitem__(self, slice, /) -> Sequence[int | tuple[str, int]]
qiskit_addon_cutting/cut_finding/disjoint_subcircuits_state.py:330: error: Invalid index type "Hashable" for "ndarray[tuple[int, ...], dtype[signedinteger[_32Bit | _64Bit]]]"; expected …
```
=> Pin numpy<2.2 in lint workflow

qiskit_addon_cutting/instructions/move.py, tox.ini
Alt text is required for accessibility.
=> Add alt text to relevant images

INSTALL.rst, README.md, docs/conf.py, docs/index.rst, docs/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb, docs/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb, docs/tutorials/03_wire_cutting_via_move_instruction.ipynb, docs/tutorials/04_automatic_cut_finding.ipynb, releasenotes/notes/0.7/cutting-samplerv2-603b0c631a3330df.yaml, releasenotes/notes/0.7/prepare-0.7.0-48b344ae77523c34.yaml
The documentation source of truth is moving to https://quantum.cloud.ibm.com/.
=> Update intersphinx mapping URLs & others

qiskit_addon_cutting/cutting_experiments.py, qiskit_addon_cutting/cutting_reconstruction.py
This PR converts an inline math expression into a displayed equation. Soon, we will be changing how the inline expressions are showed on the website and we need to transform long expressions to have a better visualization of them and avoid any possible overflow.
Even though, the current expression looks good on the website right now, it will soon break if we don't apply this change. 
This is an example of the final render:
=> Convert inline math into displayed equation to avoid overflowing in the future
