Qiskit/qiskit-addon-cutting

circuit_knitting_toolbox/circuit_cutting/wire_cutting/wire_cutting.py, tox.ini
- Simplified a for loop in wire cutting
- Updated the envlist in `tox.ini` to be correct
=> A few minor cleanups

README.md, docs/index.rst, docs/release-notes.rst
I plan to hold off on merging this until there is actually at least one thing listed under the release notes.
=> Add link from README to release notes

test/circuit_cutting/test_circuit_cutting.py
Accidentally introduced as part of #109
=> Fix importlib deprecation warning

circuit_knitting_toolbox/circuit_cutting/qpd/__init__.py, circuit_knitting_toolbox/circuit_cutting/qpd/qpd.py, test/circuit_cutting/qpd/test_qpd.py
=> Create generate_qpd_samples function

CITATION.bib, docs/index.rst
This partially addresses #128.  I also bumped the year in the citation.  We can/should update the author list soon, as well.  I built this locally, and it looks great.
=> Add bibtex note to Sphinx

test/circuit_cutting/test_cutting_roundtrip.py
=> Move roundtrip test out of `qpd` module

docs/circuit_cutting/cutqc/README.rst, docs/circuit_cutting/cutqc/index.rst
The broken links were brought to my attention on Qiskit Slack
=> Fix cutqc tutorial links

circuit_knitting_toolbox/entanglement_forging/cholesky_decomposition.py, circuit_knitting_toolbox/entanglement_forging/entanglement_forging_ground_state_solver.py
=> Remove ListOp

circuit_knitting_toolbox/circuit_cutting/cutting_evaluation.py
This is an alternative to #206, which was still causing sporadic failures for me locally.  I just tested this current change a number of times, and there were zero hangs.
If this indeed works consistently, then I suspect we can come up with a minimal test case that demonstrates the hang we were experiencing with Aer's Sampler and `PrimitiveJob` in Terra.  But before then, we can release ckt 0.2.0 without any parallel circuit evaluation.
=> Remove any attempt at using the samplers in parallel

CITATION.bib, README.md
=> Add Zenodo DOI to README and CITATION

.github/workflows/README.md
Preview at https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/blob/update-workflows-readme/.github/workflows/README.md
=> Update workflows README (add missing workflows)

.dockerignore, .github/workflows/docker.yml, .gitignore
- Add a few items to `.gitignore`
- Add `.github` to `.dockerignore`
- Add all items from `.gitignore` to `.dockerignore`, accounting for the [different syntax](https://zzz.buzz/2018/05/23/differences-of-rules-between-gitignore-and-dockerignore/).
- Re-run the Docker CI workflow if `.dockerignore` has been changed.
=> Adjust `.gitignore` and `.dockerignore`

circuit_knitting/cutting/cutting_evaluation.py, docs/conf.py, pyproject.toml
=> Configure Intersphinx to docs

circuit_knitting/cutting/cutting_evaluation.py, circuit_knitting/cutting/cutting_experiments.py, test/cutting/test_cutting_evaluation.py, test/cutting/test_cutting_experiments.py
=> Move experiment generation code to cutting_experiments.py

.github/workflows/test_development_versions.yml
We might as well test against this too to detect any problems/breaking changes early.
=> Test against qiskit-algorithms `main` in dev version tests

.github/workflows/test_latest_versions.yml, INSTALL.rst, README.md
Cleaning up a few places where pyscf and forging are still mentioned
=> Remove mentions of pyscf and entanglement forging

circuit_knitting/cutting/cut_finding/best_first_search.py, circuit_knitting/cutting/cut_finding/circuit_interface.py, circuit_knitting/cutting/cut_finding/cutting_actions.py, circuit_knitting/cutting/cut_finding/disjoint_subcircuits_state.py, circuit_knitting/cutting/cut_finding/lo_cuts_optimizer.py, circuit_knitting/cutting/cut_finding/search_space_generator.py, circuit_knitting/cutting/cutqc/wire_cutting.py, tox.ini
- https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/use-dict-literal.html
- https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/use-list-literal.html
=> Enable pylint rules to prefer list and dict literal syntax

Dockerfile
=> Docker: fix permissions for persistent-volume

.github/workflows/docker.yml
The Docker test in this PR is expected to fail before #548 is merged and to succeed after it is merged.
=> Test that `persistent-volume` is writable under Docker Compose

circuit_knitting/__init__.py
With this:
```
$ python -c "import circuit_knitting; print(circuit_knitting.__version__)"
0.7.1
```
This essentially follows what we used to do at https://github.com/qiskit-community/quantum-prototype-template/blob/main/prototype_template/__init__.py.
=> Set package `__version__` attribute

docs/circuit_cutting/tutorials/README.rst
Missing a tutorial in the readme
=> update tutorial readme

circuit_knitting/cutting/qpd/instructions/qpd_gate.py, pyproject.toml
=> Bump ruff to version 0.5.2

README.md, docs/index.rst
=> Update deprecation policy

.github/workflows/test_latest_versions.yml
I don't have understanding of the root cause, but I am trying this to see if https://github.com/actions/runner-images/issues/10636 is a factor.
=> Fix latest version tests

pyproject.toml, qiskit_addon_cutting/qpd/decompose.py, releasenotes/notes/bump-qiskit-30bb4efa538e5ef0.yaml
Ref https://github.com/Qiskit/qiskit/issues/14018
=> Add compatibility with Qiskit 2.0

docs/tutorials/01_gate_cutting_to_reduce_circuit_width.ipynb, docs/tutorials/02_gate_cutting_to_reduce_circuit_depth.ipynb, docs/tutorials/03_wire_cutting_via_move_instruction.ipynb, test/test_cutting_roundtrip.py, test/test_cutting_workflows.py
See https://github.com/Qiskit/documentation/pull/2786
=> Update `.preset_passmanagers` import to current best practice
